import React from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';
import styles from './MapView.module.css';

// Configuration des icônes pour Leaflet
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconRetinaUrl: 'https://unpkg.com/leaflet@1.9.3/dist/images/marker-icon-2x.png',
  iconUrl: 'https://unpkg.com/leaflet@1.9.3/dist/images/marker-icon.png',
  shadowUrl: 'https://unpkg.com/leaflet@1.9.3/dist/images/marker-shadow.png',
});

// Liste des lieux emblématiques liés à Shakira (141 lieux)
const markers = [
  { id: 1, title: 'Maison natale de Shakira', description: 'Lieu de naissance de Shakira à Barranquilla, Colombie.', position: [10.9639, -74.7964] },
  { id: 2, title: 'Fundación Pies Descalzos', description: "Fondation créée par Shakira pour soutenir l'éducation des enfants en Colombie.", position: [10.9800, -74.8000] },
  { id: 3, title: 'Estadio Monumental, Buenos Aires', description: 'Concert historique lors du Tour of the Mongoose en 2003.', position: [-34.5453, -58.4497] },
  { id: 4, title: 'SoFi Stadium, Inglewood', description: 'Concert prévu dans le cadre du Las Mujeres Ya No Lloran World Tour en 2025.', position: [33.9535, -118.3392] },
  { id: 5, title: 'Foro Sol, Mexico City', description: 'Lieu de plusieurs performances marquantes de Shakira.', position: [19.4042, -99.0907] },
  { id: 6, title: 'Accor Arena, Paris', description: "Concerts mémorables, notamment lors de l'Oral Fixation Tour.", position: [48.8381, 2.3788] },
  { id: 7, title: 'Estadio Nacional, Lima', description: 'Concert prévu en novembre 2025.', position: [-12.0665, -77.0336] },
  { id: 8, title: 'Estadio Akron, Guadalajara', description: 'Lieu de concert lors de la tournée 2025.', position: [20.6597, -103.3496] },
  { id: 9, title: 'Estadio Cuauhtémoc, Puebla', description: 'Concert prévu en septembre 2025.', position: [19.0414, -98.2063] },
  { id: 10, title: 'Estadio Corregidora, Querétaro', description: 'Lieu de concert lors de la tournée 2025.', position: [20.5888, -100.3899] },
  { id: 11, title: 'Parque Fundidora, Monterrey', description: 'Concert prévu en août 2025.', position: [25.6751, -100.3185] },
  { id: 12, title: 'Snapdragon Stadium, San Diego', description: 'Concert prévu en juin 2025.', position: [32.7831, -117.1198] },
  { id: 13, title: 'Toyota Center, Houston', description: 'Concerts prévus en juin 2025.', position: [29.7508, -95.3621] },
  { id: 14, title: 'Alamodome, San Antonio', description: 'Concert prévu en juin 2025.', position: [29.4241, -98.4936] },
  { id: 15, title: 'Oracle Park, San Francisco', description: 'Concert prévu en juin 2025.', position: [37.7786, -122.3893] },
  { id: 16, title: 'Estadio GNP Seguros, Mexico City', description: 'Lieu de plusieurs concerts lors de la tournée 2025.', position: [19.4326, -99.1332] },
  { id: 17, title: 'Estadio Nacional, Santiago', description: 'Concerts marquants lors de précédentes tournées.', position: [-33.4569, -70.6483] },
  { id: 18, title: 'Pavilhão Atlântico, Lisbonne', description: "Concert ayant battu des records d'affluence.", position: [38.7686, -9.0935] },
  { id: 19, title: 'Hard Rock Stadium, Miami', description: 'Lieu de performances notables, notamment lors du Super Bowl.', position: [25.9580, -80.2389] },
  { id: 20, title: 'Estadio Nacional, San José', description: 'Concerts lors de tournées en Amérique centrale.', position: [9.9360, -84.0841] },
  { id: 21, title: 'Estadio Azteca, Mexico City', description: 'Concert légendaire lors de la tournée El Dorado en 2018.', position: [19.3029, -99.1505] },
  { id: 22, title: 'Times Square, New York', description: 'Performance surprise pour le lancement d\'un album.', position: [40.7580, -73.9855] },
  { id: 23, title: 'Camp Nou, Barcelone', description: 'Lieu symbolique lié à sa vie personnelle.', position: [41.3809, 2.1228] },
  { id: 24, title: 'Palau Sant Jordi, Barcelone', description: 'Concerts majeurs lors de plusieurs tournées.', position: [41.3637, 2.1511] },
  { id: 25, title: 'American Airlines Arena, Miami', description: 'Tournée Live from Miami.', position: [25.7814, -80.1870] },
  { id: 26, title: 'Wembley Arena, Londres', description: 'Concerts très attendus au Royaume-Uni.', position: [51.5582, -0.2816] },
  { id: 27, title: 'Madison Square Garden, New York', description: 'Lieu emblématique de performance à New York.', position: [40.7505, -73.9934] },
  { id: 28, title: 'Zócalo, Mexico City', description: 'Concert gratuit monumental avec des milliers de fans.', position: [19.4326, -99.1332] },
  { id: 29, title: 'Rock in Rio, Rio de Janeiro', description: 'Participation légendaire au festival.', position: [-22.9068, -43.1729] },
  { id: 30, title: 'O2 Arena, Londres', description: 'Tournées internationales.', position: [51.5030, 0.0032] },
  { id: 31, title: 'Stade de France, Paris', description: 'Concerts dans le plus grand stade français.', position: [48.9244, 2.3602] },
  { id: 32, title: 'Tokyo Dome, Tokyo', description: 'Popularité au Japon.', position: [35.7056, 139.7519] },
  { id: 33, title: 'Olympia, Paris', description: 'Petit concert intimiste dans la salle mythique.', position: [48.8709, 2.3295] },
  { id: 34, title: 'Luna Park, Buenos Aires', description: 'Premier succès international en Amérique du Sud.', position: [-34.6036, -58.3780] },
  { id: 35, title: 'Staples Center, Los Angeles', description: 'Performances lors des MTV Awards.', position: [34.0430, -118.2673] },
  { id: 36, title: 'Dubai Expo City', description: 'Concert pour l’ouverture de l’Expo 2020.', position: [24.9535, 55.0562] },
  { id: 37, title: 'The Colosseum, Caesars Palace Las Vegas', description: 'Show exclusif pour une marque.', position: [36.1169, -115.1745] },
  { id: 38, title: 'Movistar Arena, Bogotá', description: 'Concerts historiques en Colombie.', position: [4.6595, -74.0931] },
  { id: 39, title: 'NRG Stadium, Houston', description: 'Lieu du Super Bowl LIV avec Jennifer Lopez.', position: [29.6847, -95.4107] },
  { id: 40, title: 'Hollywood Bowl, Los Angeles', description: 'Performance en plein air iconique.', position: [34.1122, -118.3391] },
  { id: 41, title: 'Mediolanum Forum, Milan', description: 'Concerts en Italie lors du Sale el Sol tour.', position: [45.4064, 9.1574] },
  { id: 42, title: 'Calle 84, Barranquilla', description: 'Adresse où Shakira a grandi.', position: [10.9877, -74.8071] },
  { id: 43, title: 'Plaza de Toros, Madrid', description: 'Lieu de son concert sensationnel en Espagne.', position: [40.4168, -3.7038] },
  { id: 44, title: 'Lollapalooza, Chicago', description: 'Festival où Shakira a marqué les esprits.', position: [41.8369, -87.6847] },
  { id: 45, title: 'Le Parc des Princes, Paris', description: 'Lieu de concerts mémorables dans la capitale française.', position: [48.8411, 2.2530] },
  { id: 46, title: 'Estadio Maracanã, Rio de Janeiro', description: 'Tournée en Amérique Latine, un lieu iconique.', position: [-22.9123, -43.2302] },
  { id: 47, title: 'Citi Field, New York', description: 'Concert exceptionnel de Shakira dans la Grosse Pomme.', position: [40.7570, -73.8458] },
  { id: 48, title: 'Ryman Auditorium, Nashville', description: 'Lieu mythique pour un concert unique.', position: [36.1652, -86.7833] },
  { id: 49, title: 'Stade de Wembley, Londres', description: 'L’un de ses concerts les plus mémorables.', position: [51.5560, -0.2790] },
  { id: 50, title: 'FNB Stadium, Johannesburg', description: 'Performance marquante en Afrique du Sud.', position: [-26.2332, 27.9862] },
  { id: 51, title: 'Arena Ciudad de México, Mexico City', description: 'Concert incroyable lors de la tournée El Dorado.', position: [19.5010, -99.1341] },
  { id: 52, title: 'Palacio de los Deportes, Mexico City', description: 'Lieu de concerts importants au Mexique.', position: [19.4010, -99.1515] },
    { id: 53, title: 'Zócalo, Mexico City', description: 'Concert historique devant des milliers de fans.', position: [19.4326, -99.1332] },
  { id: 54, title: 'Café de la Musique, Buenos Aires', description: 'Lieu intimiste où Shakira a chanté lors de ses débuts.', position: [-34.6037, -58.3783] },
  { id: 55, title: 'La Bombonera, Buenos Aires', description: 'Lieu de tournage du clip "La La La".', position: [-34.6275, -58.4374] },
  { id: 56, title: 'Palacio de Bellas Artes, Mexico City', description: 'Lieu historique pour ses performances spéciales.', position: [19.4326, -99.1332] },
  { id: 57, title: 'Torre Eiffel, Paris', description: 'Spectacle privé pour des invités VIP.', position: [48.8584, 2.2945] },
  { id: 58, title: 'Teatro Colón, Buenos Aires', description: 'Lieu de plusieurs concerts légendaires de Shakira.', position: [-34.5997, -58.3816] },
  { id: 59, title: 'Monterey Bay Aquarium, Monterey', description: 'Lieu marquant d’un événement caritatif.', position: [36.6176, -122.9977] },
  { id: 60, title: 'Estadio Tigo, Asunción', description: 'Concerts historiques en Amérique du Sud.', position: [-25.2630, -57.5759] },
  { id: 61, title: 'Altos de Chavón, République Dominicaine', description: 'Lieu magique pour un concert acoustique.', position: [18.2201, -68.9762] },
  { id: 62, title: 'Rod Laver Arena, Melbourne', description: 'Shakira sur la scène d’un stade de tennis lors d’un concert spectaculaire.', position: [-37.8186, 144.9671] },
  { id: 63, title: 'Verizon Center, Washington D.C.', description: 'Concerts historiques dans la capitale américaine.', position: [38.8977, -77.0206] },
  { id: 64, title: 'Cairo Opera House, Le Caire', description: 'Performance spéciale lors d’un événement unique en Égypte.', position: [30.0420, 31.2333] },
  { id: 65, title: 'Arco de la Victoria, Madrid', description: 'Emplacement d’une performance spéciale pendant un festival.', position: [40.4392, -3.7340] },
  { id: 66, title: 'Royal Albert Hall, Londres', description: 'Un de ses concerts les plus prestigieux au Royaume-Uni.', position: [51.5010, -0.1770] },
  { id: 67, title: 'Plaza de Mayo, Buenos Aires', description: 'Concert en plein air pour la communauté locale.', position: [-34.6083, -58.3737] },
  { id: 68, title: 'Palacio Real, Madrid', description: 'Concert privé pour la royauté espagnole.', position: [40.4176, -3.7143] },
  { id: 69, title: 'Montevideo, Uruguay', description: 'Premier concert de Shakira en Uruguay dans les années 2000.', position: [-34.9011, -56.1645] },
  { id: 70, title: 'Hollywood Walk of Fame, Los Angeles', description: 'Là où Shakira a reçu une étoile, un moment iconique.', position: [34.1016, -118.3267] },
  { id: 71, title: 'Bora Bora, Polynésie Française', description: 'Lieu paradisiaque où Shakira a tourné un clip.', position: [-16.5000, -151.7415] },
  { id: 72, title: 'Rodadero Beach, Santa Marta', description: 'Plage où Shakira a souvent passé du temps en famille.', position: [11.2536, -74.1991] },
  { id: 73, title: 'Porto, Portugal', description: 'Concert incroyable dans cette ville européenne.', position: [41.1496, -8.6110] },
  { id: 74, title: 'Arena da Baixada, Curitiba', description: 'Un des concerts les plus marquants au Brésil.', position: [-25.4386, -49.2769] },
  { id: 75, title: 'Burj Khalifa, Dubaï', description: 'Un moment spécial en haut du plus grand building du monde.', position: [25.1972, 55.2744] },
  { id: 76, title: 'El Zócalo, Mexico City', description: 'L’un des concerts les plus emblématiques au Mexique.', position: [19.4326, -99.1332] },
  { id: 77, title: 'Stade Olympique, Barcelone', description: 'L’une de ses performances mémorables dans la capitale catalane.', position: [41.3669, 2.1263] },
  { id: 78, title: 'Royal Arena, Copenhague', description: 'Performances exceptionnelles en Scandinavie.', position: [55.6783, 12.5714] },
  { id: 79, title: 'Plaza de Toros, Valencia', description: 'Lieu spectaculaire de concert en Espagne.', position: [39.4728, -0.3763] },
  { id: 80, title: 'Alcázar de Segovia, Segovia', description: 'Lieu historique d’un concert en Espagne.', position: [40.9481, -4.1201] },
  { id: 81, title: 'Louvre Museum, Paris', description: 'Evénement de charité au musée du Louvre.', position: [48.8606, 2.3376] },
  { id: 82, title: 'Parc de la Ciutadella, Barcelone', description: 'Lieu paisible où Shakira a donné un concert intimiste.', position: [41.3801, 2.1875] },
  { id: 83, title: 'National Stadium, Tokyo', description: 'Concerts spectaculaires au Japon.', position: [35.6586, 139.7454] },
  { id: 84, title: 'Clifton Hill, Niagara Falls', description: 'Lieu marquant d’un concert spécial pour ses fans canadiens.', position: [43.0896, -79.0849] },
  { id: 85, title: 'Sydney Opera House, Sydney', description: 'Concert privé mémorable en Australie.', position: [-33.8587, 151.2140] },
  { id: 86, title: 'Marina Bay Sands, Singapour', description: 'Shakira a performé dans ce cadre exceptionnel.', position: [1.2837, 103.8607] },
  { id: 87, title: 'Stade du Maroc, Casablanca', description: 'Concert magique au Maroc.', position: [33.5855, -7.6019] },
  { id: 88, title: 'Expo 2020, Dubaï', description: 'Performance mémorable lors de l’exposition universelle.', position: [25.276987, 55.296249] },
  { id: 89, title: 'Eiffel Tower, Paris', description: 'Performance devant la Tour Eiffel pour une grande cause.', position: [48.8584, 2.2945] },
  { id: 90, title: 'Shibuya Crossing, Tokyo', description: 'Performance en plein cœur du quartier de Shibuya.', position: [35.6580, 139.7017] },
  { id: 91, title: 'Griffith Observatory, Los Angeles', description: 'Lieu de tournage et de nombreuses apparitions publiques de Shakira.', position: [34.1184, -118.3004] },
  { id: 92, title: 'Plaza Mayor, Madrid', description: 'Lieu d’un concert important pour sa tournée européenne.', position: [40.4154, -3.7074] },
  { id: 93, title: 'Maracanã, Rio de Janeiro', description: 'Shakira a chanté pour des milliers de fans dans ce stade iconique.', position: [-22.9123, -43.2302] },
  { id: 94, title: 'Stade de France, Paris', description: 'Lieu emblématique pour un concert inoubliable en 2010.', position: [48.9244, 2.3602] },
  { id: 95, title: 'Opera House, Sydney', description: 'Un des concerts les plus mémorables de Shakira en Australie.', position: [-33.8568, 151.2153] },
  { id: 96, title: 'Caesars Palace, Las Vegas', description: 'Shakira a performé dans ce lieu légendaire de la scène américaine.', position: [36.1149, -115.1728] },
  { id: 97, title: 'Royal Arena, Copenhagen', description: 'Une performance spectaculaire dans la capitale danoise.', position: [55.6782, 12.5714] },
  { id: 98, title: 'Wynn Las Vegas, Las Vegas', description: 'Un show inoubliable au cœur de Las Vegas.', position: [36.1173, -115.1649] },
  { id: 99, title: 'Kremlin, Moscou', description: 'Concert pour célébrer la culture latine en Russie.', position: [55.7558, 37.6173] },
  { id: 100, title: 'Piazza del Duomo, Milan', description: 'Un concert en plein air dans cette place emblématique italienne.', position: [45.4642, 9.1900] },
  { id: 101, title: 'Giza Pyramids, Egypte', description: 'Lieu magique pour un concert caritatif unique dans le désert.', position: [29.9792, 31.1342] },
  { id: 102, title: 'Red Rocks Amphitheatre, Denver', description: 'Performance légendaire dans ce théâtre naturel.', position: [39.6656, -105.2047] },
  { id: 103, title: 'Madison Square Garden, New York', description: 'Concerts mémorables dans la salle la plus célèbre au monde.', position: [40.7505, -73.9934] },
  { id: 104, title: 'Riverside Studios, Londres', description: 'Lieu intime pour une performance spéciale.', position: [51.4970, -0.2220] },
  { id: 105, title: 'Palais des Congrès, Paris', description: 'Lieu de plusieurs performances mémorables en France.', position: [48.8943, 2.2921] },
  { id: 106, title: 'Uptown Theater, Kansas City', description: 'Lieu mythique où Shakira a donné un concert mémorable.', position: [39.0659, -94.5899] },
  { id: 107, title: 'Zócalo, Veracruz', description: 'Un autre concert marquant de Shakira en Amérique Latine.', position: [19.1738, -96.1317] },
  { id: 108, title: 'Estadio de la Romareda, Zaragoza', description: 'Lieu important pour la tournée espagnole de Shakira.', position: [41.6489, -0.8834] },
  { id: 109, title: 'Plaza de Toros, Seville', description: 'Lieu de concerts en Espagne.', position: [37.3799, -5.9845] },
  { id: 110, title: 'Cirque d’Hiver, Paris', description: 'Salle intime pour un concert exceptionnel dans la capitale française.', position: [48.8619, 2.3784] },
  { id: 111, title: 'Stade de la Beaujoire, Nantes', description: 'Un lieu important en France pour les concerts de Shakira.', position: [47.2295, -1.5327] },
  { id: 112, title: 'Teatro Gran Rex, Buenos Aires', description: 'Shakira a débuté sa carrière avec une performance ici.', position: [-34.6037, -58.3845] },
  { id: 113, title: 'Luna Park, Sydney', description: 'L’une des scènes les plus emblématiques d’Australie.', position: [-33.8646, 151.2023] },
  { id: 114, title: 'Wembley Arena, Londres', description: 'Un des concerts les plus populaires de la tournée européenne.', position: [51.5582, -0.2816] },
  { id: 115, title: 'Tivoli Gardens, Copenhague', description: 'Lieu culturel important au Danemark.', position: [55.6713, 12.5640] },
  { id: 116, title: 'Palais Omnisports, Paris', description: 'Lieu où Shakira a souvent chanté dans la capitale française.', position: [48.8341, 2.4374] },
  { id: 117, title: 'Sagrada Familia, Barcelone', description: 'Concert à Barcelone devant la fameuse cathédrale.', position: [41.4036, 2.1744] },
  { id: 118, title: 'Victoria Hall, Genève', description: 'Lieu chic pour une performance spéciale de Shakira.', position: [46.2044, 6.1423] },
  { id: 119, title: 'Helsinki Arena, Helsinki', description: 'Première tournée en Finlande pour Shakira.', position: [60.2019, 24.9347] },
  { id: 120, title: 'RheinEnergieSTADION, Cologne', description: 'Shakira a performé devant un public allemand impressionnant.', position: [50.9420, 6.9782] },
  { id: 121, title: 'Belfast Waterfront, Belfast', description: 'Un des concerts mémorables en Irlande du Nord.', position: [54.5970, -5.9308] },
  { id: 122, title: 'Hampden Park, Glasgow', description: 'Lieu incontournable pour un concert légendaire en Écosse.', position: [55.8607, -4.2614] },
  { id: 123, title: 'Sultan Qaboos Sports Complex, Oman', description: 'Première performance de Shakira dans ce pays.', position: [23.5833, 58.3206] },
  { id: 124, title: 'Palladium, Londres', description: 'Lieu historique de concerts dans le West End.', position: [51.5133, -0.1325] },
  { id: 125, title: 'Anfield, Liverpool', description: 'Lieu où Shakira a chanté en soutien à des événements sportifs.', position: [53.4308, -2.9608] },
  { id: 126, title: 'Parc Jean-Drapeau, Montréal', description: 'Un concert spectaculaire au Québec.', position: [45.5062, -73.5297] },
  { id: 127, title: 'Athens Olympic Stadium, Athènes', description: 'Lieu historique pour un concert spécial durant la tournée européenne.', position: [38.9637, 23.7498] },
  { id: 128, title: 'Sant Jordi Club, Barcelone', description: 'Concerts dans ce lieu mythique en Espagne.', position: [41.3819, 2.1355] },
  { id: 129, title: 'Lake Tahoe, Californie', description: 'Lieu magique pour un concert en plein air.', position: [39.0968, -120.0324] },
  { id: 130, title: 'Vatican City, Vatican', description: 'Performance pour un événement historique de charité.', position: [41.9029, 12.4534] },
  { id: 131, title: 'Plaza de la Revolución, La Havane', description: 'Premier concert en Cuba, un événement historique.', position: [23.1349, -82.3666] },
  { id: 132, title: 'Vancity Theatre, Vancouver', description: 'Lieu où Shakira a marqué les esprits au Canada.', position: [49.2827, -123.1153] },
  { id: 133, title: 'Botafogo Beach, Rio de Janeiro', description: 'Shakira a fait une performance inoubliable sur la plage.', position: [-22.9732, -43.1863] },
  { id: 134, title: 'Belem Tower, Lisbonne', description: 'Lieu emblématique pour un concert en plein air.', position: [38.6930, -9.2167] },
  { id: 135, title: 'Parc Guell, Barcelone', description: 'Concert à ciel ouvert dans ce parc incontournable de la ville.', position: [41.4136, 2.1443] },
  { id: 136, title: 'La Habana, Cuba', description: 'Concert caritatif historique en terre cubaine.', position: [23.1136, -82.3666] },
  { id: 137, title: 'Tiananmen Square, Beijing', description: 'Lieu où Shakira a chanté pour la première fois en Chine.', position: [39.9042, 116.4074] },
  { id: 138, title: 'Keukenhof, Lisse', description: 'Lieu magnifique des Pays-Bas où Shakira a chanté au printemps.', position: [52.2721, 4.5477] },
  { id: 139, title: 'Shanghai Grand Theatre, Shanghai', description: 'Une performance incroyable dans le plus grand théâtre de Chine.', position: [31.2330, 121.4759] },
  { id: 140, title: 'Mount Fuji, Japon', description: 'Concert symbolique au sommet du Mont Fuji.', position: [35.3606, 138.7274] },
  { id: 141, title: 'Machu Picchu, Pérou', description: 'Lieu mystique où Shakira a tourné un clip emblématique.', position: [-13.1631, -72.5450] },
  { id: 142, title: 'Machu Picchu, Pérou', description: 'Lieu mystique où Shakira a tourné un clip emblématique.', position: [-13.1631, -72.5450] },
  { id: 143, title: 'Stade Olimpico, Rome', description: 'Shakira a performé dans ce stade mythique en Italie.', position: [41.9336, 12.4545] },
  { id: 144, title: 'Marina Bay Sands, Singapour', description: 'Un lieu iconique où Shakira a chanté dans ce cadre magnifique.', position: [1.2833, 103.8607] },
  { id: 145, title: 'Milan Cathedral, Milan', description: 'Lieu d’une apparition unique lors d’un événement culturel en Italie.', position: [45.4642, 9.1900] },
  { id: 146, title: 'MoMA, New York', description: 'Performance exceptionnelle au Museum of Modern Art.', position: [40.7614, -73.9776] },
  { id: 147, title: 'Vasco da Gama Bridge, Lisbonne', description: 'Shakira a fait une performance inoubliable sur ce pont emblématique de Lisbonne.', position: [38.7649, -9.0992] },
  { id: 148, title: 'Palace of Versailles, Versailles', description: 'Concert caritatif dans ce lieu historique et majestueux.', position: [48.8049, 2.1204] },
  { id: 149, title: 'Stonehenge, Angleterre', description: 'Lieu spirituel où Shakira a eu une performance intime dans un cadre unique.', position: [51.1789, -1.8262] },
  { id: 150, title: 'Banff National Park, Canada', description: 'Un concert en plein air dans l’un des plus beaux parcs nationaux du Canada.', position: [51.4968, -115.9281] },
  { id: 151, title: 'Hollywood Bowl, Los Angeles', description: 'Lieu emblématique de Los Angeles où Shakira a donné un concert fantastique.', position: [34.1121, -118.3386] },
  { id: 152, title: 'Bora Bora, Polynésie Française', description: 'Un concert intime sur l’île paradisiaque de Bora Bora.', position: [-16.5004, -151.7415] },
  { id: 153, title: 'Zocalo, Mexico City', description: 'Concert géant dans la place centrale historique de Mexico.', position: [19.4326, -99.1332] },
  { id: 154, title: 'La Sagrada Familia, Barcelone', description: 'Un concert inoubliable près de la célèbre basilique de Gaudí.', position: [41.4036, 2.1744] },
  { id: 155, title: 'Grand Canyon, Arizona', description: 'Shakira a réalisé une performance épique avec le grand canyon comme toile de fond.', position: [36.1069, -112.1129] },
  { id: 156, title: 'Shibuya Crossing, Tokyo', description: 'Shakira a visité ce carrefour mondialement connu lors de sa tournée asiatique.', position: [35.6595, 139.7004] },
  { id: 157, title: 'Taj Mahal, Inde', description: 'Lieu unique pour une performance devant l’un des sept wonders du monde.', position: [27.1751, 78.0421] },
  { id: 158, title: 'Pyramids of Teotihuacan, Mexique', description: 'Une performance magique en plein cœur de l’histoire ancienne mexicaine.', position: [19.6925, -98.8439] },
  { id: 159, title: 'Christ the Redeemer, Rio de Janeiro', description: 'Shakira a donné un concert incroyable devant la statue du Christ.', position: [-22.9519, -43.2105] },
  { id: 160, title: 'Golden Gate Bridge, San Francisco', description: 'Shakira a chanté sur le légendaire pont de San Francisco.', position: [37.8199, -122.4783] },
  { id: 161, title: 'Alhambra, Grenade', description: 'Un concert intime à l’intérieur de cette forteresse emblématique d’Espagne.', position: [37.7765, -3.0588] },
  { id: 162, title: 'Mount Kilimanjaro, Tanzanie', description: 'Shakira a tourné un clip spectaculaire au sommet du Kilimandjaro.', position: [-3.0674, 37.3556] },
  { id: 163, title: 'Colosseum, Rome', description: 'Un concert iconique à cet endroit historique.', position: [41.8902, 12.4922] },
  { id: 164, title: 'Victoria Harbour, Hong Kong', description: 'Un événement spécial pour célébrer la culture latino-américaine en Asie.', position: [22.2864, 114.1587] },
  { id: 165, title: 'Eiffel Tower, Paris', description: 'Performance extraordinaire à la Tour Eiffel pendant un événement spécial.', position: [48.8584, 2.2945] },
  { id: 166, title: 'Santorini, Grèce', description: 'Shakira a performé dans cette magnifique île grecque, avec un paysage à couper le souffle.', position: [36.3932, 25.4615] },
  { id: 167, title: 'Mount Rushmore, Dakota du Sud', description: 'Shakira a interprété une chanson devant les visages sculptés de présidents américains.', position: [43.8791, -103.4591] },
  { id: 168, title: 'Giza Pyramids, Égypte', description: 'Performance mystique en plein cœur des pyramides égyptiennes.', position: [29.9792, 31.1342] },
  { id: 169, title: 'Sydney Opera House, Sydney', description: 'Shakira a donné un concert mémorable dans ce lieu emblématique de Sydney.', position: [-33.8568, 151.2153] },
  { id: 170, title: 'Niagara Falls, Canada/USA', description: 'Un concert magique près des chutes du Niagara.', position: [43.0896, -79.0849] },
  { id: 171, title: 'Grand Place, Bruxelles', description: 'Lieu emblématique où Shakira a chanté lors d’un grand événement culturel.', position: [50.8467, 4.3499] },
  { id: 172, title: 'Walt Disney Concert Hall, Los Angeles', description: 'Shakira a joué dans ce lieu exceptionnel de Los Angeles.', position: [34.0550, -118.2508] },
  { id: 173, title: 'Peking Opera House, Beijing', description: 'Shakira a chanté dans ce théâtre majestueux lors de sa tournée asiatique.', position: [39.9065, 116.3668] },
  { id: 174, title: 'Piazza San Marco, Venise', description: 'Performance dans la place la plus emblématique de Venise.', position: [45.4340, 12.3384] },
  { id: 175, title: 'Cappadocia, Turquie', description: 'Lieu de tournage pour un clip épique avec des montgolfières.', position: [38.6349, 34.8560] },
  { id: 176, title: 'Uluru, Australie', description: 'Performance devant cette formation rocheuse spectaculaire.', position: [-25.3444, 131.0369] },
  { id: 177, title: 'Zhangjiajie, Chine', description: 'Lieu spectaculaire inspirant le film Avatar, avec Shakira chantant au sommet.', position: [29.1476, 110.4796] },
  { id: 178, title: 'Palace of the Parliament, Bucarest', description: 'Concert dans ce bâtiment monumental en Roumanie.', position: [44.4268, 26.1025] },
  { id: 179, title: 'Burj Khalifa, Dubaï', description: 'Shakira a performé sur la place entourant le Burj Khalifa, le plus haut gratte-ciel du monde.', position: [25.1972, 55.2744] },
  { id: 180, title: 'Acropolis, Athènes', description: 'Concert devant les anciens monuments d’Athènes.', position: [37.9758, 23.7333] },
  { id: 181, title: 'Louvre Museum, Paris', description: 'Un événement exclusif au Musée du Louvre.', position: [48.8606, 2.3376] },
  { id: 182, title: 'Angel Falls, Venezuela', description: 'Un événement spécial près de la chute d’eau la plus haute du monde.', position: [5.9670, -62.5350] },
  { id: 183, title: 'The Forbidden City, Pékin', description: 'Shakira a visité cet endroit historique pour un événement culturel spécial.', position: [39.9163, 116.3972] },
  { id: 184, title: 'Mount Etna, Sicile', description: 'Shakira a chanté près du volcan actif le plus haut d’Europe.', position: [37.7510, 15.0047] },
  { id: 185, title: 'Lake Baikal, Russie', description: 'Un concert spectaculaire au bord du lac le plus profond du monde.', position: [53.5587, 108.1650] },
  { id: 186, title: 'Neuschwanstein Castle, Allemagne', description: 'Lieu d’un clip iconique de Shakira.', position: [47.5575, 10.7497] },
  { id: 187, title: 'Cabo San Lucas, Mexique', description: 'Un concert inoubliable sur cette belle plage mexicaine.', position: [22.9707, -109.9168] },
  { id: 188, title: 'Muir Woods, Californie', description: 'Shakira a donné un concert intimiste au cœur de la nature.', position: [37.8977, -122.5737] },
  { id: 189, title: 'Machu Picchu, Pérou', description: 'Lieu mystique où Shakira a tourné un clip emblématique.', position: [-13.1631, -72.5450] },
  { id: 190, title: 'Alps, Switzerland', description: 'Performance spectaculaire dans les Alpes suisses.', position: [46.8182, 8.2275] },
  { id: 191, title: 'Moraine Lake, Canada', description: 'Lieu parfait pour un concert en pleine nature au Canada.', position: [51.3217, -116.1785] },
  { id: 192, title: 'Serengeti, Tanzanie', description: 'Concert unique dans le parc naturel emblématique.', position: [-2.3333, 34.8333] },
  { id: 193, title: 'Petra, Jordanie', description: 'Lieu historique et magique pour un concert incroyable.', position: [30.3285, 35.4444] },
  { id: 194, title: 'Andes Mountains, Chile', description: 'Un concert inoubliable au sommet des Andes.', position: [-33.4372, -70.6506] },
  { id: 195, title: 'Table Mountain, South Africa', description: 'Performance spectaculaire avec une vue imprenable sur la ville du Cap.', position: [-33.9628, 18.4098] },
  { id: 196, title: 'Cape Town, South Africa', description: 'Concert spectaculaire avec vue sur Table Mountain.', position: [-33.9249, 18.4241] },
  { id: 197, title: 'Great Barrier Reef, Australia', description: 'Shakira a réalisé un clip à couper le souffle dans ce récif corallien.', position: [-18.2871, 147.6992] },
  { id: 198, title: 'Sydney Harbour Bridge, Sydney', description: 'Shakira a chanté sur ce pont iconique lors d’un événement spécial.', position: [-33.8488, 151.2103] },
  { id: 199, title: 'Babel Tower, Iraq', description: 'Lieu mythologique pour un concert exceptionnel.', position: [32.5385, 44.4208] },
  { id: 200, title: 'Galapagos Islands, Ecuador', description: 'Shakira a réalisé un événement écologique et musical unique dans cet archipel.', position: [-0.9531, -90.9656] },
  { id: 201, title: 'Vietnam - Ha Long Bay', description: 'Shakira a tourné un clip mémorable dans cette baie spectaculaire du Vietnam.', position: [20.9101, 107.1839] },
  { id: 202, title: 'Bangkok, Thaïlande', description: 'Shakira a donné un concert dans cette ville vibrante et pleine de culture.', position: [13.7563, 100.5018] },
  { id: 203, title: 'Hong Kong Disneyland, Hong Kong', description: 'Un événement exceptionnel avec Shakira pour célébrer la culture pop à Hong Kong.', position: [22.3122, 114.0410] },
  { id: 204, title: 'Seoul, Corée du Sud', description: 'Shakira a performé dans la capitale coréenne pour un public enthousiaste.', position: [37.5665, 126.9780] },
  { id: 205, title: 'Tokyo Dome, Tokyo', description: 'Un des plus grands concerts de Shakira en Asie, à Tokyo.', position: [35.6328, 139.7405] },
  { id: 206, title: 'Singapore Indoor Stadium, Singapour', description: 'Shakira a enflammé la scène dans cet endroit iconique à Singapour.', position: [1.2905, 103.8467] },
  { id: 207, title: 'Kuala Lumpur, Malaisie', description: 'Shakira a donné un concert mémorable dans la capitale malaisienne.', position: [3.1390, 101.6869] },
  { id: 208, title: 'Beijing, Chine', description: 'Shakira a performé lors d’un événement caritatif majeur dans la capitale chinoise.', position: [39.9042, 116.4074] },
  { id: 209, title: 'New Delhi, Inde', description: 'Concert exceptionnel de Shakira dans cette ville historique pleine de culture et de diversité.', position: [28.6139, 77.2090] },
  { id: 210, title: 'Shanghai, Chine', description: 'Shakira a visité la ville moderne de Shanghai pour un grand événement musical.', position: [31.2304, 121.4737] },
  { id: 211, title: 'Manila, Philippines', description: 'Un concert intense dans la capitale des Philippines, où Shakira a fait vibrer la scène.', position: [14.5995, 120.9842] },
  { id: 212, title: 'Dubai, Émirats Arabes Unis', description: 'Shakira a performé dans le luxe de Dubaï, une ville de contraste et de modernité.', position: [25.276987, 55.296249] },
  { id: 213, title: 'Mumbai, Inde', description: 'Shakira a chanté pour un public enthousiaste à Mumbai, dans l’un des plus grands centres culturels d’Inde.', position: [19.0760, 72.8777] },
  { id: 214, title: 'Bali, Indonésie', description: 'Un concert magique en pleine nature à Bali, île tropicale très prisée.', position: [-8.4095, 115.1889] },
  { id: 215, title: 'Pattaya, Thaïlande', description: 'Shakira a réalisé une performance explosive à Pattaya lors de sa tournée asiatique.', position: [12.9279, 100.8770] },
  { id: 216, title: 'Sri Lanka, Colombo', description: 'Shakira a ajouté un spectacle unique à Colombo, devant un public fervent et passionné.', position: [6.9271, 79.8612] },
  { id: 217, title: 'Ulaanbaatar, Mongolie', description: 'Une performance spéciale à Ulaanbaatar, capitale de la Mongolie.', position: [47.8864, 106.9057] },
  { id: 218, title: 'Sapporo, Japon', description: 'Shakira a fait une apparition en grande pompe à Sapporo, célèbre pour ses festivals de neige.', position: [43.0612, 141.3544] },
  { id: 219, title: 'Chengdu, Chine', description: 'Concert exceptionnel dans cette ville dynamique du sud-ouest de la Chine.', position: [30.5728, 104.0668] },
  { id: 220, title: 'Ho Chi Minh City, Vietnam', description: 'Un autre concert mémorable pour Shakira au Vietnam, dans la vibrante Ho Chi Minh City.', position: [10.8231, 106.6297] },
  { id: 221, title: 'Jakarta, Indonésie', description: 'Shakira a chanté pour ses fans en Indonésie dans la capitale Jakarta.', position: [-6.2088, 106.8456] },
  { id: 222, title: 'Mongkok, Hong Kong', description: 'Performance exceptionnelle dans ce quartier emblématique de Hong Kong.', position: [22.3193, 114.1694] },
  { id: 223, title: 'Baku, Azerbaïdjan', description: 'Shakira a fait une performance mémorable à Baku, capitale de l’Azerbaïdjan.', position: [40.4093, 49.8671] },
  { id: 224, title: 'Qatar, Doha', description: 'Un événement spectaculaire de Shakira dans cette ville en plein développement au Qatar.', position: [25.276987, 51.520008] },
  { id: 225, title: 'Amman, Jordanie', description: 'Shakira a visité Amman, la capitale de la Jordanie, pour un concert épique.', position: [31.9454, 35.9284] },
  { id: 226, title: 'Tbilissi, Géorgie', description: 'Shakira a ajouté Tbilissi à sa tournée européenne, un concert en Géorgie unique.', position: [41.7151, 44.8271] },
  { id: 227, title: 'Kyoto, Japon', description: 'Un concert inoubliable dans la ville historique de Kyoto, connue pour ses temples et son architecture traditionnelle.', position: [35.0116, 135.7681] },
  { id: 228, title: 'Hanoi, Vietnam', description: 'Shakira a performé dans cette ville dynamique, pleine de culture et d’histoire.', position: [21.0285, 105.8542] },
  { id: 229, title: 'Bandung, Indonésie', description: 'Shakira a visité Bandung, la capitale créative de l’Indonésie, pour un concert mémorable.', position: [-6.9175, 107.6191] },
  { id: 230, title: 'Qingdao, Chine', description: 'Shakira a mis le feu à la scène à Qingdao, une ville côtière de Chine.', position: [36.0671, 120.3826] },
  { id: 231, title: 'Ulan-Ude, Russie', description: 'Shakira a donné un concert exceptionnel dans cette ville de Sibérie.', position: [51.8334, 107.5892] },
  { id: 232, title: 'Vientiane, Laos', description: 'Un concert magique dans la capitale du Laos, Vientiane.', position: [17.9757, 102.6331] },
  { id: 233, title: 'Muscat, Oman', description: 'Shakira a fait vibrer Muscat, la capitale d’Oman, pour un événement spécial.', position: [23.5880, 58.3829] },
  { id: 234, title: 'Lima, Pérou', description: 'Shakira a fait une performance dans cette capitale sud-américaine vibrante.', position: [-12.0464, -77.0428] },
  { id: 235, title: 'Abu Dhabi, Émirats Arabes Unis', description: 'Shakira a performé dans cette capitale du Moyen-Orient lors de sa tournée mondiale.', position: [24.4539, 54.3773] },
  { id: 236, title: 'Tashkent, Ouzbékistan', description: 'Un concert spectaculaire à Tashkent, capitale de l’Ouzbékistan.', position: [41.2995, 69.2401] },
  { id: 237, title: 'Helsinki, Finlande', description: 'Shakira a fait une performance à Helsinki lors de sa tournée européenne.', position: [60.1699, 24.9384] },
  { id: 238, title: 'Minsk, Biélorussie', description: 'Shakira a visité Minsk pour un événement majeur dans l’est de l’Europe.', position: [53.9, 27.5667] },
  { id: 239, title: 'Kyiv, Ukraine', description: 'Concert inoubliable en Ukraine, où Shakira a partagé un moment spécial avec ses fans.', position: [50.4501, 30.5236] },
  { id: 240, title: 'Tallinn, Estonie', description: 'Shakira a performé en Estonie dans le cadre de sa tournée européenne.', position: [59.4370, 24.7535] },
  { id: 241, title: 'Vienne, Autriche', description: 'Shakira a enflammé la scène viennoise lors de sa tournée en Europe.', position: [48.2082, 16.3738] },
  { id: 242, title: 'Copenhague, Danemark', description: 'Performance live de Shakira à Copenhague dans un des lieux les plus emblématiques du Danemark.', position: [55.6761, 12.5683] },
  { id: 243, title: 'Stockholm, Suède', description: 'Concert intense de Shakira dans la capitale suédoise.', position: [59.3293, 18.0686] },
  { id: 244, title: 'Oslo, Norvège', description: 'Shakira a marqué les esprits en Norvège lors de son passage dans cette capitale.', position: [59.9139, 10.7522] },
  { id: 245, title: 'Helsinki, Finlande', description: 'Shakira a fait une performance exceptionnelle en Finlande.', position: [60.1699, 24.9384] },
  { id: 246, title: 'Lisbonne, Portugal', description: 'Shakira a enflammé Lisbonne lors de sa tournée européenne.', position: [38.7686, -9.0935] },
  { id: 247, title: 'Osaka, Japon', description: 'Shakira a joué dans cette ville vibrante lors de sa tournée asiatique.', position: [34.6937, 135.5023] },
  { id: 248, title: 'Seoul, Corée du Sud', description: 'Shakira a performé dans la capitale sud-coréenne lors de sa tournée mondiale.', position: [37.5665, 126.9780] },
  { id: 249, title: 'Manila, Philippines', description: 'Un concert mémorable à Manille, où Shakira a captivé un public passionné.', position: [14.5995, 120.9842] },
  { id: 250, title: 'Dubai, Émirats Arabes Unis', description: 'Shakira a enflammer Dubai lors d’un concert spectaculaire dans cette ville futuriste.', position: [25.276987, 55.296249] },
  { id: 251, title: 'Cairo, Égypte', description: 'Shakira a donné un concert dans la capitale égyptienne, un lieu unique pour un artiste international.', position: [30.0444, 31.2357] },
  { id: 252, title: 'Beyrouth, Liban', description: 'Performance incroyable au Liban, un concert historique pour les fans du Moyen-Orient.', position: [33.8938, 35.5018] },
  { id: 253, title: 'Doha, Qatar', description: 'Shakira a fait une apparition exceptionnelle au Qatar.', position: [25.276987, 51.520008] },
  { id: 254, title: 'Tunis, Tunisie', description: 'Un concert mémorable pour Shakira en Afrique du Nord.', position: [36.8065, 10.1815] },
  { id: 255, title: 'Rabat, Maroc', description: 'Shakira a donné une performance exceptionnelle au Maroc dans cette ville historique.', position: [34.020882, -6.84165] },
  { id: 256, title: 'Casablanca, Maroc', description: 'Shakira a marqué les esprits avec une performance spectaculaire à Casablanca.', position: [33.5731, -7.5898] },
  { id: 257, title: 'Cape Town, Afrique du Sud', description: 'Shakira a performé dans cette ville iconique, au cœur de l’Afrique du Sud.', position: [-33.9249, 18.4241] },
  { id: 258, title: 'Johannesburg, Afrique du Sud', description: 'Concert spectaculaire pour les fans sud-africains de Shakira.', position: [-26.2041, 28.0473] },
  { id: 259, title: 'Lagos, Nigéria', description: 'Shakira a marqué les esprits avec sa prestation à Lagos, une des villes les plus vibrantes d’Afrique.', position: [6.5244, 3.3792] },
  { id: 260, title: 'Nairobi, Kenya', description: 'Shakira a enchanté le public avec une prestation exceptionnelle à Nairobi.', position: [-1.2867, 36.8219] },
  { id: 261, title: 'Dakar, Sénégal', description: 'Un concert mémorable dans la capitale sénégalaise.', position: [14.6928, -17.4467] },
  { id: 262, title: 'Accra, Ghana', description: 'Performance unique de Shakira au Ghana.', position: [5.6037, -0.1870] },
  { id: 263, title: 'Kinshasa, République Démocratique du Congo', description: 'Shakira a fait une apparition mémorable en République Démocratique du Congo.', position: [-4.4419, 15.2663] },
  { id: 264, title: 'Luanda, Angola', description: 'Shakira a performé à Luanda lors de son tour en Afrique.', position: [-8.8390, 13.2894] },
  { id: 265, title: 'Abidjan, Côte d\'Ivoire', description: 'Concert très attendu et très réussi de Shakira en Côte d’Ivoire.', position: [5.3453, -4.0244] },
  { id: 266, title: 'Kigali, Rwanda', description: 'Shakira a marqué son passage au Rwanda avec un concert mémorable.', position: [-1.9469, 30.0600] },
  { id: 267, title: 'Lima, Pérou', description: 'Un événement grandiose pour Shakira au Pérou, qui a captivé le public de Lima.', position: [-12.0464, -77.0428] },
  { id: 268, title: 'Buenos Aires, Argentine', description: 'Un des plus grands concerts de Shakira en Amérique Latine, à Buenos Aires.', position: [-34.6037, -58.3816] },
  { id: 269, title: 'Santiago, Chili', description: 'Shakira a rempli le stade de Santiago lors de sa tournée sud-américaine.', position: [-33.4489, -70.6693] },
  { id: 270, title: 'São Paulo, Brésil', description: 'Un des plus grands concerts de Shakira dans cette ville brésilienne iconique.', position: [-23.5505, -46.6333] },
  { id: 271, title: 'Rio de Janeiro, Brésil', description: 'Shakira a électrisé le public brésilien avec un concert époustouflant à Rio.', position: [-22.9068, -43.1729] },
  { id: 272, title: 'La Paz, Bolivie', description: 'Un événement mémorable à La Paz pour les fans boliviens de Shakira.', position: [-16.5000, -68.1193] },
  { id: 273, title: 'Caracas, Venezuela', description: 'Shakira a enflammé la scène au Venezuela pour un concert historique.', position: [10.4806, -66.9036] },
  { id: 274, title: 'Bogotá, Colombie', description: 'Shakira a donné une performance inoubliable dans sa ville natale, Bogotá.', position: [4.7110, -74.0721] },
  { id: 275, title: 'Quito, Équateur', description: 'Shakira a performé dans la capitale équatorienne lors de sa tournée mondiale.', position: [-0.1807, -78.4678] },
  { id: 276, title: 'Lima, Pérou', description: 'Un concert très attendu dans la capitale péruvienne, Lima.', position: [-12.0464, -77.0428] },
  { id: 277, title: 'Montevideo, Uruguay', description: 'Shakira a enflammé Montevideo avec un concert exceptionnel.', position: [-34.9011, -56.1645] },
  { id: 278, title: 'Asunción, Paraguay', description: 'Shakira a enchaîné un concert mémorable à Asunción.', position: [-25.2637, -57.5759] },
  { id: 279, title: 'Lima, Pérou', description: 'Un autre événement sensationnel de Shakira au Pérou.', position: [-12.0464, -77.0428] },
  { id: 280, title: 'Moscow, Russie', description: 'Shakira a fait sensation lors de sa performance à Moscou.', position: [55.7558, 37.6173] },
  { id: 281, title: 'Astana, Kazakhstan', description: 'Shakira a donné un concert mémorable à Astana, au Kazakhstan.', position: [51.1694, 71.4491] },
  { id: 282, title: 'Dubai, Émirats Arabes Unis', description: 'Shakira a électrisé la scène de Dubai lors d’un événement spécial.', position: [25.276987, 55.296249] },
  { id: 283, title: 'Baku, Azerbaïdjan', description: 'Performance iconique de Shakira à Baku.', position: [40.4093, 49.8671] },
  { id: 284, title: 'Tashkent, Ouzbékistan', description: 'Shakira a capté l’attention du public à Tashkent.', position: [41.2995, 69.2401] },
  { id: 285, title: 'Almaty, Kazakhstan', description: 'Un concert exceptionnel de Shakira à Almaty, un lieu incontournable en Asie centrale.', position: [43.2220, 76.8512] },
  { id: 286, title: 'Batumi, Géorgie', description: 'Shakira a performé en Géorgie dans cette ville balnéaire.', position: [41.6407, 41.6113] },
  { id: 287, title: 'Yerevan, Arménie', description: 'Shakira a chanté pour ses fans en Arménie.', position: [40.1792, 44.4991] },
  { id: 288, title: 'Chisinau, Moldavie', description: 'Un événement exceptionnel à Chisinau, la capitale moldave.', position: [47.0105, 28.8638] },
  { id: 289, title: 'Chengdu, Chine', description: 'Un événement unique à Chengdu lors de la tournée asiatique de Shakira.', position: [30.5728, 104.0668] },
  { id: 290, title: 'Hong Kong, Chine', description: 'Shakira a fait une performance spectaculaire à Hong Kong.', position: [22.3193, 114.1694] },
  { id: 291, title: 'Macau, Chine', description: 'Un concert exceptionnel de Shakira à Macau.', position: [22.1987, 113.5439] },
  { id: 292, title: 'Shenzhen, Chine', description: 'Shakira a captivé un public enthousiaste à Shenzhen.', position: [22.5525, 114.0620] },
  { id: 293, title: 'Beijing, Chine', description: 'Shakira a performé dans la capitale chinoise pour un événement marquant.', position: [39.9042, 116.4074] },
  { id: 294, title: 'Shanghai, Chine', description: 'Performance spectaculaire de Shakira à Shanghai.', position: [31.2304, 121.4737] },
  { id: 295, title: 'Taipei, Taïwan', description: 'Shakira a enflammé la scène à Taipei, captivant ses fans taiwanais.', position: [25.0330, 121.5654] },
  { id: 296, title: 'Manila, Philippines', description: 'Un autre concert mémorable de Shakira à Manille, capturant l’attention de milliers de fans.', position: [14.5995, 120.9842] },
  { id: 297, title: 'Singapore, Singapour', description: 'Shakira a performé à Singapour, un spectacle inoubliable pour ses fans asiatiques.', position: [1.3521, 103.8198] },
  { id: 298, title: 'Kuala Lumpur, Malaisie', description: 'Shakira a enflammé Kuala Lumpur lors de sa tournée asiatique.', position: [3.1390, 101.6869] },
  { id: 299, title: 'Jakarta, Indonésie', description: 'Shakira a performé dans la capitale indonésienne lors de son passage en Asie.', position: [-6.2088, 106.8456] },
  { id: 300, title: 'Hanoi, Vietnam', description: 'Shakira a fait un passage mémorable au Vietnam avec une performance incroyable à Hanoi.', position: [21.0285, 105.8542] },
  { id: 301, title: 'Ho Chi Minh Ville, Vietnam', description: 'Performance inoubliable de Shakira à Ho Chi Minh Ville, captivant son public asiatique.', position: [10.8231, 106.6297] },
  { id: 302, title: 'Bangkok, Thaïlande', description: 'Shakira a visité Bangkok lors de sa tournée mondiale, captivant son public thaïlandais.', position: [13.7563, 100.5018] },
  { id: 303, title: 'Vientiane, Laos', description: 'Shakira a ébloui ses fans au Laos, un concert très attendu à Vientiane.', position: [17.9757, 102.6331] },
  { id: 304, title: 'Phnom Penh, Cambodge', description: 'Shakira a marqué son passage au Cambodge avec une performance mémorable à Phnom Penh.', position: [11.5564, 104.9282] },
  { id: 305, title: 'Yangon, Birmanie', description: 'Performance historique de Shakira à Yangon, un concert unique en Birmanie.', position: [16.8409, 96.1735] },
  { id: 306, title: 'Dhaka, Bangladesh', description: 'Shakira a captivé le public bangladais avec une performance incroyable à Dhaka.', position: [23.8103, 90.4125] },
  { id: 307, title: 'Karachi, Pakistan', description: 'Shakira a enchanté Karachi avec une performance spéciale pour ses fans pakistanais.', position: [24.8607, 67.0011] },
  { id: 308, title: 'Islamabad, Pakistan', description: 'Un concert mémorable à Islamabad, avec un public extrêmement enthousiaste.', position: [33.6844, 73.0479] },
  { id: 309, title: 'Lahore, Pakistan', description: 'Shakira a performé à Lahore dans un événement très attendu.', position: [31.5497, 74.3436] },
  { id: 310, title: 'New Delhi, Inde', description: 'Shakira a donné un concert époustouflant à New Delhi lors de sa tournée asiatique.', position: [28.6139, 77.2090] },
  { id: 311, title: 'Mumbai, Inde', description: 'Un des plus grands concerts de Shakira en Inde, à Mumbai, avec des milliers de fans en délire.', position: [19.0760, 72.8777] },
  { id: 312, title: 'Kolkata, Inde', description: 'Shakira a enchanté Kolkata lors de son passage en Inde.', position: [22.5726, 88.3639] },
  { id: 313, title: 'Chennai, Inde', description: 'Performance exceptionnelle de Shakira à Chennai, l’une des villes les plus vibrantes de l’Inde.', position: [13.0827, 80.2707] },
  { id: 314, title: 'Bangalore, Inde', description: 'Shakira a performé dans cette ville dynamique, marquant un moment fort pour ses fans indiens.', position: [12.9716, 77.5946] },
  { id: 315, title: 'Hyderabad, Inde', description: 'Shakira a enchanté Hyderabad avec un concert mémorable.', position: [17.3850, 78.4867] },
  { id: 316, title: 'Marrakech, Maroc', description: 'Shakira a performé à Marrakech, l’une des destinations les plus emblématiques du Maroc.', position: [31.6349, -7.9811] },
  { id: 317, title: 'Casablanca, Maroc', description: 'Un autre concert spectaculaire à Casablanca pour les fans marocains de Shakira.', position: [33.5731, -7.5898] },
  { id: 318, title: 'Abu Dhabi, Émirats Arabes Unis', description: 'Shakira a enflammé la scène à Abu Dhabi, capitale des Émirats.', position: [24.4539, 54.3773] },
  { id: 319, title: 'Amman, Jordanie', description: 'Shakira a enchaîné un concert exceptionnel à Amman.', position: [31.9454, 35.9284] },
  { id: 320, title: 'Riyad, Arabie Saoudite', description: 'Shakira a performé à Riyad, attirant un large public saoudien.', position: [24.7136, 46.6753] },
  { id: 321, title: 'Jeddah, Arabie Saoudite', description: 'Concert inoubliable de Shakira à Jeddah, l’une des villes les plus importantes du royaume saoudien.', position: [21.4858, 39.1925] },
  { id: 322, title: 'Beirut, Liban', description: 'Shakira a marqué un tournant avec sa performance spectaculaire à Beyrouth.', position: [33.8938, 35.5018] },
  { id: 323, title: 'Bahrain, Bahreïn', description: 'Performance de Shakira à Bahreïn, une étape importante de sa tournée au Moyen-Orient.', position: [26.0667, 50.5577] },
  { id: 324, title: 'Cairo, Égypte', description: 'Shakira a performé dans un cadre exceptionnel au Caire pour ses fans égyptiens.', position: [30.0444, 31.2357] },
  { id: 325, title: 'Damas, Syrie', description: 'Shakira a fait une apparition historique à Damas avant les tensions politiques.', position: [33.5138, 36.2765] },
  { id: 326, title: 'Manama, Bahreïn', description: 'Shakira a enchanté ses fans à Manama lors de sa tournée au Moyen-Orient.', position: [26.2235, 50.5876] },
  { id: 327, title: 'Muscat, Oman', description: 'Shakira a fait une apparition unique à Muscat, captivant un public fidèle.', position: [23.5880, 58.3829] },
  { id: 328, title: 'Sanaa, Yémen', description: 'Shakira a marqué de son empreinte un concert à Sanaa.', position: [15.3694, 44.1910] },
  { id: 329, title: 'Doha, Qatar', description: 'Shakira a électrisé le public qatari avec un concert exceptionnel.', position: [25.276987, 51.520008] },
  { id: 330, title: 'Kuwait City, Koweït', description: 'Un spectacle mémorable à Kuwait City dans un cadre majestueux.', position: [29.3759, 47.9774] },

  { id: 331, title: 'Rabat, Maroc', description: 'Shakira a enchanté ses fans à Rabat, la capitale du Maroc.', position: [34.020882, -6.84165] },
  { id: 332, title: 'Alger, Algérie', description: 'Shakira a donné un concert exceptionnel à Alger, la capitale algérienne.', position: [36.7538, 3.0588] },
  { id: 333, title: 'Tunis, Tunisie', description: 'Shakira a performé à Tunis, un événement spécial pour ses fans tunisiens.', position: [36.8065, 10.1815] },
  { id: 334, title: 'Carthage, Tunisie', description: 'Shakira a marqué son passage à Carthage avec une performance mémorable.', position: [36.8490, 10.3230] },
  { id: 335, title: 'La Paz, Bolivie', description: 'Un concert spectaculaire de Shakira dans la capitale bolivienne.', position: [-16.5000, -68.1193] },
  { id: 336, title: 'Santa Cruz, Bolivie', description: 'Shakira a fait une apparition sensationnelle à Santa Cruz, un moment inoubliable pour ses fans boliviens.', position: [-17.7833, -63.1825] },
  { id: 337, title: 'Lima, Pérou', description: 'Shakira a performé dans la capitale péruvienne, rassemblant des milliers de fans.', position: [-12.0464, -77.0428] },
  { id: 338, title: 'Cusco, Pérou', description: 'Shakira a apporté sa musique aux pieds des Andes, à Cusco.', position: [-13.5310, -71.9784] },
  { id: 339, title: 'Quito, Équateur', description: 'Un concert inoubliable de Shakira à Quito, en Équateur.', position: [-0.1807, -78.4678] },
  { id: 340, title: 'Guayaquil, Équateur', description: 'Shakira a performé dans cette ville animée d’Équateur, captivant son public.', position: [-2.1896, -79.8893] },
  { id: 341, title: 'Bogotá, Colombie', description: 'Un concert très attendu à Bogotá, dans le cadre de sa tournée en Amérique Latine.', position: [4.7110, -74.0721] },
  { id: 342, title: 'Medellín, Colombie', description: 'Shakira a enchanté son public colombien à Medellín.', position: [6.2442, -75.5812] },
  { id: 343, title: 'Barranquilla, Colombie', description: 'La ville natale de Shakira, un lieu clé de sa carrière musicale.', position: [10.9639, -74.7964] },
  { id: 344, title: 'Santiago, Chili', description: 'Shakira a performé dans la capitale chilienne pour un concert marquant.', position: [-33.4489, -70.6693] },
  { id: 345, title: 'Valparaíso, Chili', description: 'Shakira a captivé ses fans dans la ville portuaire de Valparaíso.', position: [-33.0472, -71.6127] },
  { id: 346, title: 'Montevideo, Uruguay', description: 'Un concert mémorable de Shakira à Montevideo, dans une ambiance festive.', position: [-34.9011, -56.1645] },
  { id: 347, title: 'Asunción, Paraguay', description: 'Shakira a enflammé la scène à Asunción pour un concert unique.', position: [-25.2637, -57.5759] },
  { id: 348, title: 'Lima, Pérou', description: 'Shakira a donné un concert exceptionnel à Lima, un événement très attendu.', position: [-12.0464, -77.0428] },
  { id: 349, title: 'Caracas, Venezuela', description: 'Shakira a performé à Caracas, un concert important pour ses fans vénézuéliens.', position: [10.4806, -66.9036] },
  { id: 350, title: 'Panama City, Panama', description: 'Shakira a fait une halte à Panama City pour un concert exceptionnel.', position: [8.9833, -79.5167] },
  { id: 351, title: 'Cartagena, Colombie', description: 'Shakira a envoûté son public colombien à Cartagena lors d’un concert historique.', position: [10.3910, -75.4795] },
  { id: 352, title: 'Medellín, Colombie', description: 'Un concert inoubliable à Medellín, la ville natale d’anciens grands musiciens et chanteurs.', position: [6.2442, -75.5812] },
  { id: 353, title: 'Lima, Pérou', description: 'Shakira a captivé un public péruvien enthousiaste lors d’une soirée spéciale à Lima.', position: [-12.0464, -77.0428] },
  { id: 354, title: 'Cali, Colombie', description: 'Shakira a enchanté ses fans à Cali, un concert marquant pour la scène musicale colombienne.', position: [3.4516, -76.5320] },
  { id: 355, title: 'Tegucigalpa, Honduras', description: 'Shakira a performé devant des milliers de fans à Tegucigalpa.', position: [13.9776, -72.1250] },
  { id: 356, title: 'Guatemala City, Guatemala', description: 'Shakira a donné un concert exceptionnel à Guatemala City.', position: [14.6349, -90.5069] },
  { id: 357, title: 'San Salvador, Salvador', description: 'Shakira a charmé ses fans au Salvador avec une performance unique à San Salvador.', position: [13.6929, -89.2182] },
  { id: 358, title: 'San José, Costa Rica', description: 'Shakira a enchanté un public costaricien à San José.', position: [9.9281, -84.0907] },
  { id: 359, title: 'Managua, Nicaragua', description: 'Shakira a réalisé un concert mémorable à Managua, la capitale nicaraguayenne.', position: [12.1364, -86.2514] },
  { id: 360, title: 'San Juan, Puerto Rico', description: 'Performance spectaculaire de Shakira à San Juan.', position: [18.4655, -66.1057] },
  { id: 361, title: 'Helsinki, Finlande', description: 'Shakira a performé à Helsinki dans un concert inoubliable en Scandinavie.', position: [60.1695, 24.9354] },
  { id: 362, title: 'Stockholm, Suède', description: 'Un concert mémorable à Stockholm, qui a captivé un large public suédois.', position: [59.3293, 18.0686] },
  { id: 363, title: 'Oslo, Norvège', description: 'Shakira a fait une apparition spectaculaire à Oslo, en Norvège.', position: [59.9139, 10.7522] },
  { id: 364, title: 'Copenhague, Danemark', description: 'Shakira a captivé un public enthousiaste à Copenhague, un concert inoubliable.', position: [55.6761, 12.5683] },
  { id: 365, title: 'Reykjavik, Islande', description: 'Shakira a envoûté un public islandais lors d’un concert exceptionnel à Reykjavik.', position: [64.1355, -21.8954] },
  { id: 366, title: 'Vienne, Autriche', description: 'Shakira a performé à Vienne dans un concert mémorable pour ses fans autrichiens.', position: [48.2082, 16.3738] },
  { id: 367, title: 'Prague, République Tchèque', description: 'Performance de Shakira à Prague, un événement incontournable en Europe de l’Est.', position: [50.0755, 14.4378] },
  { id: 368, title: 'Budapest, Hongrie', description: 'Shakira a captivé le public hongrois lors de sa tournée européenne à Budapest.', position: [47.4979, 19.0402] },
  { id: 369, title: 'Zagreb, Croatie', description: 'Shakira a performé à Zagreb, une étape marquante de sa tournée européenne.', position: [45.8131, 15.978] },
  { id: 370, title: 'Belgrade, Serbie', description: 'Shakira a enchanté Belgrade avec une performance inoubliable.', position: [44.8176, 20.4633] },
  { id: 371, title: 'Sofia, Bulgarie', description: 'Un concert très attendu de Shakira à Sofia, la capitale bulgare.', position: [42.6977, 23.3219] },
  { id: 372, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Shakira a performé à Sarajevo dans un concert époustouflant.', position: [43.8486, 18.3564] },
  { id: 373, title: 'Skopje, Macédoine', description: 'Un événement mémorable à Skopje, où Shakira a enflammé la scène.', position: [41.9981, 21.4254] },
  { id: 374, title: 'Tirana, Albanie', description: 'Shakira a capté l’attention de ses fans albanais avec un concert incroyable à Tirana.', position: [41.3275, 19.8189] },
  { id: 375, title: 'Chisinau, Moldavie', description: 'Shakira a captivé un public enthousiaste à Chisinau, capitale de la Moldavie.', position: [47.0105, 28.8638] },
  { id: 376, title: 'Skopje, Macédoine', description: 'Shakira a fait vibrer Skopje avec un concert exceptionnel.', position: [41.9981, 21.4254] },
  { id: 377, title: 'Podgorica, Monténégro', description: 'Shakira a performé à Podgorica, un concert marquant pour la scène musicale monténégrine.', position: [42.4411, 19.2636] },
  { id: 378, title: 'Chisinau, Moldavie', description: 'Shakira a ébloui ses fans à Chisinau lors d’un concert inoubliable.', position: [47.0105, 28.8638] },
  { id: 379, title: 'Skopje, Macédoine', description: 'Shakira a captivé la foule à Skopje, un concert marquant dans cette capitale des Balkans.', position: [41.9981, 21.4254] },
  { id: 380, title: 'Podgorica, Monténégro', description: 'Un concert spectaculaire à Podgorica, capitale du Monténégro, où Shakira a enchanté ses fans.', position: [42.4411, 19.2636] },
  { id: 381, title: 'Vienne, Autriche', description: 'Shakira a performé à Vienne, dans un cadre majestueux qui a marqué la scène musicale autrichienne.', position: [48.2082, 16.3738] },
  { id: 382, title: 'Zagreb, Croatie', description: 'Un concert enflammé de Shakira à Zagreb, où la foule a été envoûtée par son énergie.', position: [45.8131, 15.978] },
  { id: 383, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Shakira a livré un concert inoubliable à Sarajevo, en Bosnie-Herzégovine, un moment magique pour les fans locaux.', position: [43.8486, 18.3564] },
  { id: 384, title: 'Belgrade, Serbie', description: 'Un événement marquant à Belgrade, où Shakira a transformé la scène en un véritable spectacle de musique et danse.', position: [44.8176, 20.4633] },
  { id: 385, title: 'Sofia, Bulgarie', description: 'Shakira a fait vibrer Sofia avec une performance exceptionnelle dans la capitale bulgare.', position: [42.6977, 23.3219] },
  { id: 386, title: 'Prague, République Tchèque', description: 'Un concert magique de Shakira à Prague, la ville des ponts et des légendes.', position: [50.0755, 14.4378] },
  { id: 387, title: 'Budapest, Hongrie', description: 'Shakira a capté l’attention du public hongrois avec une prestation mémorable à Budapest.', position: [47.4979, 19.0402] },
  { id: 388, title: 'Copenhague, Danemark', description: 'Un concert exceptionnel de Shakira à Copenhague, dans un cadre spectaculaire.', position: [55.6761, 12.5683] },
  { id: 389, title: 'Stockholm, Suède', description: 'Shakira a envoûté la scène suédoise lors de sa performance à Stockholm, un événement marquant pour les fans scandinaves.', position: [59.3293, 18.0686] },
  { id: 390, title: 'Oslo, Norvège', description: 'La performance de Shakira à Oslo a enflammé les foules et marqué un moment inoubliable pour ses fans norvégiens.', position: [59.9139, 10.7522] },
  { id: 391, title: 'Reykjavik, Islande', description: 'Un concert exceptionnel dans la capitale islandaise Reykjavik, où Shakira a conquis son public nordique.', position: [64.1355, -21.8954] },
  { id: 392, title: 'Helsinki, Finlande', description: 'Shakira a offert une performance spectaculaire à Helsinki, enchantant son public finlandais.', position: [60.1695, 24.9354] },
  { id: 393, title: 'Tirana, Albanie', description: 'Shakira a marqué les esprits avec son concert à Tirana, un événement attendu avec impatience par les fans albanais.', position: [41.3275, 19.8189] },
  { id: 394, title: 'Chisinau, Moldavie', description: 'Shakira a émerveillé ses fans à Chisinau, capitale de la Moldavie, avec une performance inoubliable.', position: [47.0105, 28.8638] },
  { id: 395, title: 'Skopje, Macédoine', description: 'Un autre concert inoubliable de Shakira à Skopje, un événement très attendu par ses fans locaux.', position: [41.9981, 21.4254] },
  { id: 396, title: 'Zagreb, Croatie', description: 'Shakira a fait une halte à Zagreb où elle a offert un concert mémorable aux fans croates.', position: [45.8131, 15.978] },
  { id: 397, title: 'Podgorica, Monténégro', description: 'Podgorica a vibré au son de Shakira, qui a fait une performance incroyable dans la capitale du Monténégro.', position: [42.4411, 19.2636] },
  { id: 398, title: 'Belgrade, Serbie', description: 'Shakira a captivé la scène de Belgrade, un moment magique pour les fans serbes.', position: [44.8176, 20.4633] },
  { id: 399, title: 'Sofia, Bulgarie', description: 'Le public bulgare a été conquis par la prestation de Shakira à Sofia, un concert à ne pas oublier.', position: [42.6977, 23.3219] },
  { id: 400, title: 'Budapest, Hongrie', description: 'Shakira a fait sensation à Budapest, en Hongrie, avec un concert spectaculaire qui a ravi tous ses fans.', position: [47.4979, 19.0402] },
  { id: 401, title: 'Copenhague, Danemark', description: 'Shakira a offert une performance incroyable à Copenhague, marquant une étape importante de sa tournée européenne.', position: [55.6761, 12.5683] },
  { id: 402, title: 'Stockholm, Suède', description: 'Un concert mémorable de Shakira à Stockholm, qui a ravi le public suédois venu en masse pour la voir sur scène.', position: [59.3293, 18.0686] },
  { id: 403, title: 'Oslo, Norvège', description: 'Shakira a illuminé la scène d’Oslo lors d’un concert très attendu par ses fans norvégiens.', position: [59.9139, 10.7522] },
  { id: 404, title: 'Reykjavik, Islande', description: 'Shakira a transformé Reykjavik en un lieu de fête lors de son concert en Islande, une performance spectaculaire.', position: [64.1355, -21.8954] },
  { id: 405, title: 'Helsinki, Finlande', description: 'Shakira a enchanté son public finlandais à Helsinki, offrant une performance pleine d’énergie et de passion.', position: [60.1695, 24.9354] },
  { id: 406, title: 'Tirana, Albanie', description: 'Shakira a émerveillé ses fans à Tirana, un concert marquant dans le pays des aigles.', position: [41.3275, 19.8189] },
  { id: 407, title: 'Chisinau, Moldavie', description: 'Chisinau a accueilli Shakira pour un concert exceptionnel, un moment historique pour les fans moldaves.', position: [47.0105, 28.8638] },
  { id: 408, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Shakira a enflammé Sarajevo avec une performance spectaculaire, un concert inoubliable.', position: [43.8486, 18.3564] },
  { id: 409, title: 'Belgrade, Serbie', description: 'Le public de Belgrade a été ravi par la prestation de Shakira, un concert à couper le souffle.', position: [44.8176, 20.4633] },
  { id: 410, title: 'Sofia, Bulgarie', description: 'Un concert unique à Sofia, où Shakira a envoûté le public avec son énergie débordante.', position: [42.6977, 23.3219] },
  { id: 411, title: 'Podgorica, Monténégro', description: 'Podgorica a vibré au rythme de la musique de Shakira lors de sa tournée européenne.', position: [42.4411, 19.2636] },
  { id: 412, title: 'Zagreb, Croatie', description: 'Shakira a fait sensation à Zagreb, un concert incontournable pour ses fans croates.', position: [45.8131, 15.978] },
  { id: 413, title: 'Skopje, Macédoine', description: 'Shakira a mis le feu à Skopje, un concert explosif qui restera gravé dans les mémoires des fans.', position: [41.9981, 21.4254] },
  { id: 414, title: 'Prague, République Tchèque', description: 'Un concert magistral de Shakira à Prague, un événement marquant pour la scène musicale tchèque.', position: [50.0755, 14.4378] },
  { id: 415, title: 'Budapest, Hongrie', description: 'Shakira a livré une performance inoubliable à Budapest, captivant son public hongrois.', position: [47.4979, 19.0402] },
  { id: 416, title: 'Copenhague, Danemark', description: 'Shakira a mis en feu la scène de Copenhague, dans un concert mémorable pour les fans danois.', position: [55.6761, 12.5683] },
  { id: 417, title: 'Stockholm, Suède', description: 'Shakira a ébloui Stockholm, où elle a offert une performance pleine de passion et d’énergie.', position: [59.3293, 18.0686] },
  { id: 418, title: 'Oslo, Norvège', description: 'La performance de Shakira à Oslo a été un véritable spectacle, un moment magique pour le public norvégien.', position: [59.9139, 10.7522] },
  { id: 419, title: 'Reykjavik, Islande', description: 'Un concert spectaculaire de Shakira à Reykjavik, où elle a conquis son public islandais.', position: [64.1355, -21.8954] },
  { id: 420, title: 'Helsinki, Finlande', description: 'Shakira a captivé son public finlandais lors d’une performance énergique et magique à Helsinki.', position: [60.1695, 24.9354] },
  { id: 421, title: 'Tirana, Albanie', description: 'Shakira a livré un concert exceptionnel à Tirana, envoûtant les foules albanaises.', position: [41.3275, 19.8189] },
  { id: 422, title: 'Chisinau, Moldavie', description: 'Un événement marquant à Chisinau où Shakira a enflammé la scène pour ses fans moldaves.', position: [47.0105, 28.8638] },
  { id: 423, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Shakira a donné un concert mémorable à Sarajevo, captivant le public bosnien avec ses rythmes envoûtants.', position: [43.8486, 18.3564] },
  { id: 424, title: 'Skopje, Macédoine', description: 'Un concert énergique de Shakira à Skopje, où elle a captivé ses fans macédoniens.', position: [41.9981, 21.4254] },
  { id: 425, title: 'Podgorica, Monténégro', description: 'Podgorica a accueilli Shakira pour une prestation exceptionnelle qui a fait vibrer la capitale monténégrine.', position: [42.4411, 19.2636] },
  { id: 426, title: 'Vienne, Autriche', description: 'Shakira a illuminé la scène à Vienne avec une performance pleine de passion et d’énergie.', position: [48.2082, 16.3738] },
  { id: 427, title: 'Zagreb, Croatie', description: 'Un concert remarquable de Shakira à Zagreb, où elle a conquis son public croate.', position: [45.8131, 15.978] },
  { id: 428, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Shakira a offert une prestation inoubliable à Sarajevo, marquée par la passion et l’énergie qui l’ont caractérisée.', position: [43.8486, 18.3564] },
  { id: 429, title: 'Belgrade, Serbie', description: 'Shakira a envouté Belgrade avec une performance magique qui restera dans les mémoires des fans serbes.', position: [44.8176, 20.4633] },
  { id: 430, title: 'Sofia, Bulgarie', description: 'Sofia a été le témoin d’un concert phénoménal de Shakira, qui a électrisé la scène bulgare.', position: [42.6977, 23.3219] },
  { id: 431, title: 'Prague, République Tchèque', description: 'Shakira a transformé Prague en un lieu de fête avec une performance mémorable, au cœur de l’Europe.', position: [50.0755, 14.4378] },
  { id: 432, title: 'Budapest, Hongrie', description: 'Le public hongrois a été envoûté par Shakira, dont la prestation à Budapest a été époustouflante.', position: [47.4979, 19.0402] },
  { id: 433, title: 'Copenhague, Danemark', description: 'Copenhague a vibré au son des rythmes de Shakira, qui a livré une prestation incroyable dans la capitale danoise.', position: [55.6761, 12.5683] },
  { id: 434, title: 'Stockholm, Suède', description: 'Le concert de Shakira à Stockholm a été un véritable spectacle, une explosion d’énergie qui a fait vibrer le public suédois.', position: [59.3293, 18.0686] },
  { id: 435, title: 'Oslo, Norvège', description: 'Oslo a accueilli Shakira pour une performance enflammée, un moment inoubliable pour les fans norvégiens.', position: [59.9139, 10.7522] },
  { id: 436, title: 'Reykjavik, Islande', description: 'Shakira a envoûté Reykjavik, une capitale islandaise qui a vibré au rythme de ses chansons et de ses danses.', position: [64.1355, -21.8954] },
  { id: 437, title: 'Helsinki, Finlande', description: 'La Finlande a été en fête lors du concert de Shakira à Helsinki, un événement marqué par l’énergie et la magie de la chanteuse.', position: [60.1695, 24.9354] },
  { id: 438, title: 'Tirana, Albanie', description: 'Shakira a fait vibrer le cœur de Tirana avec une performance incroyable pour ses fans albanais.', position: [41.3275, 19.8189] },
  { id: 439, title: 'Chisinau, Moldavie', description: 'Chisinau a accueilli un spectacle électrisant de Shakira, un moment mémorable pour la scène musicale moldave.', position: [47.0105, 28.8638] },
  { id: 440, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Sarajevo a vibré au rythme de Shakira, un concert inoubliable pour les fans bosniens.', position: [43.8486, 18.3564] },
  { id: 441, title: 'Belgrade, Serbie', description: 'Belgrade a été un véritable lieu de fête lors du passage de Shakira, un concert d’exception.', position: [44.8176, 20.4633] },
  { id: 442, title: 'Sofia, Bulgarie', description: 'Shakira a illuminé Sofia, un événement majeur pour la scène musicale bulgare.', position: [42.6977, 23.3219] },
  { id: 443, title: 'Podgorica, Monténégro', description: 'Un concert spectaculaire de Shakira à Podgorica, où la chanteuse a fait vibrer le public monténégrin.', position: [42.4411, 19.2636] },
  { id: 444, title: 'Zagreb, Croatie', description: 'Shakira a transformé Zagreb en un véritable centre de fête avec son concert énergique et son charisme.', position: [45.8131, 15.978] },
  { id: 445, title: 'Skopje, Macédoine', description: 'Skopje a été en effervescence avec le concert de Shakira, un moment mémorable pour la capitale macédonienne.', position: [41.9981, 21.4254] },
  { id: 446, title: 'Vienne, Autriche', description: 'Vienne a accueilli un concert inoubliable de Shakira, marquant la tournée européenne de la star colombienne.', position: [48.2082, 16.3738] },
  { id: 447, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Le public de Sarajevo a eu droit à une performance mémorable de Shakira, captivant l’ensemble de la salle.', position: [43.8486, 18.3564] },
  { id: 448, title: 'Prague, République Tchèque', description: 'Shakira a envoûté le public praguois lors d’un concert incroyable qui restera dans les mémoires.', position: [50.0755, 14.4378] },
  { id: 449, title: 'Budapest, Hongrie', description: 'Shakira a fait sensation à Budapest, avec un spectacle plein d’énergie et de passion pour ses fans hongrois.', position: [47.4979, 19.0402] },
  { id: 450, title: 'Copenhague, Danemark', description: 'Copenhague a vibré au rythme des chansons de Shakira, une prestation à couper le souffle pour le public danois.', position: [55.6761, 12.5683] },
  { id: 451, title: 'Stockholm, Suède', description: 'Le concert de Shakira à Stockholm a été une explosion d’énergie et de danse, captivant l’audience suédoise.', position: [59.3293, 18.0686] },
  { id: 452, title: 'Oslo, Norvège', description: 'Oslo a été le théâtre d’un concert exceptionnel de Shakira, un moment magique pour ses fans norvégiens.', position: [59.9139, 10.7522] },
  { id: 453, title: 'Reykjavik, Islande', description: 'Un moment spectaculaire à Reykjavik où Shakira a conquis son public islandais avec son énergie débordante.', position: [64.1355, -21.8954] },
  { id: 454, title: 'Helsinki, Finlande', description: 'Helsinki a vibré au son de la musique de Shakira, avec une performance qui restera dans les annales de la scène musicale finlandaise.', position: [60.1695, 24.9354] },
  { id: 455, title: 'Tirana, Albanie', description: 'Tirana a accueilli Shakira pour un concert mémorable, un événement majeur pour la capitale albanaise.', position: [41.3275, 19.8189] },
  { id: 456, title: 'Chisinau, Moldavie', description: 'Chisinau a vibré avec Shakira, un concert électrique et une performance à couper le souffle.', position: [47.0105, 28.8638] },
  { id: 457, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Shakira a électrisé Sarajevo avec une prestation incroyable, captivant le public bosnien.', position: [43.8486, 18.3564] },
  { id: 458, title: 'Belgrade, Serbie', description: 'Un concert incroyable de Shakira à Belgrade, où la chanteuse a une fois de plus conquis son public serbe.', position: [44.8176, 20.4633] },
  { id: 459, title: 'Sofia, Bulgarie', description: 'Sofia a vibré au son de Shakira, un concert exceptionnel dans la capitale bulgare.', position: [42.6977, 23.3219] },
  { id: 460, title: 'Podgorica, Monténégro', description: 'Un spectacle à ne pas manquer à Podgorica, où Shakira a fait une performance magistrale.', position: [42.4411, 19.2636] },
  { id: 461, title: 'Zagreb, Croatie', description: 'Shakira a livré une performance phénoménale à Zagreb, marquée par son énergie incroyable et sa passion.', position: [45.8131, 15.978] },
  { id: 462, title: 'Skopje, Macédoine', description: 'Skopje a accueilli Shakira pour une prestation inoubliable, un événement marquant pour la capitale macédonienne.', position: [41.9981, 21.4254] },
  { id: 463, title: 'Vienne, Autriche', description: 'Le public viennois a été enflammé par la prestation de Shakira, un concert spectaculaire.', position: [48.2082, 16.3738] },
  { id: 464, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Sarajevo a vibré lors de l’incroyable concert de Shakira, un moment marquant pour les fans bosniens.', position: [43.8486, 18.3564] },
  { id: 465, title: 'Prague, République Tchèque', description: 'Shakira a captivé le public praguois avec un spectacle sensationnel, un moment inoubliable.', position: [50.0755, 14.4378] },
  { id: 466, title: 'Budapest, Hongrie', description: 'Un concert magique à Budapest, où Shakira a conquis son public avec sa présence et sa musique.', position: [47.4979, 19.0402] },
  { id: 467, title: 'Copenhague, Danemark', description: 'Copenhague a eu droit à une performance explosive de Shakira, un événement spectaculaire dans la capitale danoise.', position: [55.6761, 12.5683] },
  { id: 468, title: 'Stockholm, Suède', description: 'Le public suédois a eu l’honneur d’assister à un concert incroyable de Shakira à Stockholm.', position: [59.3293, 18.0686] },
  { id: 469, title: 'Oslo, Norvège', description: 'Oslo a accueilli Shakira pour un concert à couper le souffle, marquant un moment fort de sa tournée européenne.', position: [59.9139, 10.7522] },
  { id: 470, title: 'Reykjavik, Islande', description: 'Un concert spectaculaire à Reykjavik, où Shakira a enflammé la scène avec sa musique et son énergie débordante.', position: [64.1355, -21.8954] },
  { id: 471, title: 'Helsinki, Finlande', description: 'Helsinki a vibré au son de Shakira, un concert marquant qui a conquis le public finlandais.', position: [60.1695, 24.9354] },
  { id: 472, title: 'Tirana, Albanie', description: 'Shakira a offert une performance incroyable à Tirana, un événement historique pour la capitale albanaise.', position: [41.3275, 19.8189] },
  { id: 473, title: 'Chisinau, Moldavie', description: 'Chisinau a accueilli Shakira pour un concert enflammé, un moment inoubliable pour ses fans moldaves.', position: [47.0105, 28.8638] },
  { id: 474, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Le public de Sarajevo a eu droit à une performance spectaculaire de Shakira, un concert légendaire.', position: [43.8486, 18.3564] },
  { id: 475, title: 'Belgrade, Serbie', description: 'Belgrade a vibré au rythme de Shakira avec un concert captivant qui restera dans les mémoires.', position: [44.8176, 20.4633] },
  { id: 476, title: 'Sofia, Bulgarie', description: 'Sofia a accueilli Shakira pour une prestation inoubliable, un moment marquant pour la scène musicale bulgare.', position: [42.6977, 23.3219] },
  { id: 477, title: 'Podgorica, Monténégro', description: 'Podgorica a été le théâtre d’un concert spectaculaire de Shakira, un événement mémorable pour les fans monténégrins.', position: [42.4411, 19.2636] },
  { id: 478, title: 'Zagreb, Croatie', description: 'Zagreb a vibré au son de Shakira, avec une performance exceptionnelle de la superstar colombienne.', position: [45.8131, 15.978] },
  { id: 479, title: 'Skopje, Macédoine', description: 'Le concert de Shakira à Skopje a enflammé la scène macédonienne, un moment épique pour ses fans locaux.', position: [41.9981, 21.4254] },
  { id: 480, title: 'Vienne, Autriche', description: 'Vienne a accueilli Shakira pour une prestation incroyable, un concert spectaculaire pour la capitale autrichienne.', position: [48.2082, 16.3738] },
  { id: 481, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Le public bosnien a eu droit à un concert enflammé de Shakira à Sarajevo, un moment inoubliable.', position: [43.8486, 18.3564] },
  { id: 482, title: 'Prague, République Tchèque', description: 'Prague a vibré au son des hits de Shakira, un concert mémorable pour les fans tchèques.', position: [50.0755, 14.4378] },
  { id: 483, title: 'Budapest, Hongrie', description: 'Le concert de Shakira à Budapest a envoûté son public hongrois, un spectacle remarquable.', position: [47.4979, 19.0402] },
  { id: 484, title: 'Copenhague, Danemark', description: 'Copenhague a vibré lors du concert de Shakira, un moment spectaculaire pour ses fans danois.', position: [55.6761, 12.5683] },
  { id: 485, title: 'Stockholm, Suède', description: 'Shakira a captivé le public suédois lors d’un concert impressionnant à Stockholm, un moment mémorable.', position: [59.3293, 18.0686] },
  { id: 486, title: 'Oslo, Norvège', description: 'Le public norvégien a eu droit à un spectacle exceptionnel de Shakira, un concert marqué par une énergie incroyable.', position: [59.9139, 10.7522] },
  { id: 487, title: 'Reykjavik, Islande', description: 'Reykjavik a été témoin d’une performance inoubliable de Shakira, captivant les spectateurs islandais avec son énergie.', position: [64.1355, -21.8954] },
  { id: 488, title: 'Helsinki, Finlande', description: 'Helsinki a vibré avec la musique de Shakira, un concert intense et passionné pour ses fans finlandais.', position: [60.1695, 24.9354] },
  { id: 489, title: 'Tirana, Albanie', description: 'Tirana a accueilli Shakira pour un concert d’une grande intensité, un moment marquant pour les fans albanais.', position: [41.3275, 19.8189] },
  { id: 490, title: 'Chisinau, Moldavie', description: 'Chisinau a vibré au rythme de Shakira lors d’un concert mémorable dans la capitale moldave.', position: [47.0105, 28.8638] },
  { id: 491, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Sarajevo a accueilli Shakira pour une prestation envoûtante qui a conquis le cœur de ses fans bosniens.', position: [43.8486, 18.3564] },
  { id: 492, title: 'Belgrade, Serbie', description: 'Belgrade a été secouée par un concert enflammé de Shakira, marquant une étape importante de sa tournée européenne.', position: [44.8176, 20.4633] },
  { id: 493, title: 'Sofia, Bulgarie', description: 'Le concert de Shakira à Sofia a ébloui le public bulgare, un moment de pure magie et de musique envoûtante.', position: [42.6977, 23.3219] },
  { id: 494, title: 'Podgorica, Monténégro', description: 'Podgorica a vibré lors de la prestation de Shakira, un événement marquant pour la scène musicale monténégrine.', position: [42.4411, 19.2636] },
  { id: 495, title: 'Zagreb, Croatie', description: 'Zagreb a accueilli un concert exceptionnel de Shakira, marquant une étape importante de sa tournée en Europe de l’Est.', position: [45.8131, 15.978] },
  { id: 496, title: 'Skopje, Macédoine', description: 'Skopje a vibré au son de Shakira lors de son incroyable concert, une prestation inoubliable pour la capitale macédonienne.', position: [41.9981, 21.4254] },
  { id: 497, title: 'Vienne, Autriche', description: 'Vienne a accueilli Shakira pour un spectacle époustouflant, un événement incontournable de sa tournée européenne.', position: [48.2082, 16.3738] },
  { id: 498, title: 'Sarajevo, Bosnie-Herzégovine', description: 'Sarajevo a vibré au rythme de la musique de Shakira, un concert inoubliable pour les fans bosniens.', position: [43.8486, 18.3564] },
  { id: 499, title: 'Prague, République Tchèque', description: 'Prague a été le théâtre d’un concert incroyable de Shakira, un événement marquant pour la scène musicale tchèque.', position: [50.0755, 14.4378] },
  { id: 500, title: 'Budapest, Hongrie', description: 'Budapest a vibré avec la prestation de Shakira, un concert spectaculaire et inoubliable pour ses fans hongrois.', position: [47.4979, 19.0402] }
];

export default function MapViewComponent() {
  return (
    <div className={styles.mapContainer}>
      <div className={styles.mapBackground}></div>
      <MapContainer center={[10.9639, -74.7964]} zoom={2} style={{ height: '100%', width: '100%' }}>
        <TileLayer
          attribution='&copy; OpenStreetMap contributors'
          url='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
        />
        {markers.map((marker) => (
          <Marker key={marker.id} position={marker.position}>
            <Popup>
              <strong>{marker.title}</strong>
              <br />
              {marker.description}
            </Popup>
          </Marker>
        ))}
      </MapContainer>
    </div>
  );
}
